const models = [
  {
    src: "../../../models/sofa-set.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    name: "Sofas",
  },
  {
    src: "../../../models/table.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    name: "Tables",
  },
  {
    src: "../../../models/endtables.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    name: "Endtables",
  },
  {
    src: "../../../models/bowl.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
  },
  {
    src: "../../../models/lamp.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    name: "Lamps",
  },
  {
    src: "../../../models/carpet.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    name: "Carpets",
  },
  {
    src: "../../../models/lamps/lamp-2.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/lamps/lamp-3.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/lamps/lamp-4.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/lamps/lamp-5.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/lamps/lamp-6.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/lamps/lamp-7.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Lamps",
  },
  {
    src: "../../../models/sofas/sofa-1.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/sofas/sofa-2.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/sofas/sofa-3.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/sofas/sofa-4.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/sofas/sofa-5.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/sofas/sofa-6.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Sofas",
  },
  {
    src: "../../../models/endtables/endtable-1.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  // {
  //   src: "../../../models/endtables/endtable-2.gltf",
  //   position: [0, 0, 0],
  //   rotation: [0, 76.92, 0],
  //   category: "Endtables",
  // },
  {
    src: "../../../models/endtables/endtable-3.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  // {
  //   src: "../../../models/endtables/endtable-4.gltf",
  //   position: [0, 0, 0],
  //   rotation: [0, 0, 0],
  //   category: "Endtables",
  // },
  {
    src: "../../../models/endtables/endtable-5.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  {
    src: "../../../models/endtables/endtable-6.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  {
    src: "../../../models/endtables/endtable-7.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  {
    src: "../../../models/endtables/endtable-8.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  {
    src: "../../../models/endtables/endtable-9.gltf",
    position: [0, 0, 0],
    rotation: [0, 76.92, 0],
    category: "Endtables",
  },
  {
    src: "../../../models/tables/table-2.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
  {
    src: "../../../models/tables/table-3.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
  {
    src: "../../../models/tables/table-4.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
  {
    src: "../../../models/tables/table-5.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
  {
    src: "../../../models/tables/table-6.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
  {
    src: "../../../models/tables/table-1.gltf",
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    category: "Tables",
  },
];

export default models;
