/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -T chair-set-1.glb
Files: chair-set-1.glb [3.61MB] > chair-set-1-transformed.glb [1.26MB] (65%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from '@react-three/fiber'

export function ChairSet(props) {
  const { nodes, materials } = useGLTF('../../../models/chair-set-1-transformed.glb')
  const chairRef = useRef()

  useFrame(({ clock }) => {
    chairRef.current.rotation.y = clock.getElapsedTime() / 2
  })

  return (


    <group {...props} dispose={null} ref={chairRef}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Wood} position={[-0.569, 0.502, 0.006]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Fabric Pattern 03']} position={[0.513, 0.516, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('../../../models/chair-set-1-transformed.glb')
