/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -T scene.glb
Files: scene.glb [458.01MB] > scene-transformed.glb [11.08MB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('../../../models/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
     <pointLight position={[0, 20, 10]} intensity={1.5} />
      <mesh geometry={nodes.Plane.geometry} material={materials.PaletteMaterial009} position={[2.665, 0.05, 1.492]} rotation={[0, -0.959, 0]} scale={-11.933} />
      <group position={[3.529, 2.31, 1.754]} scale={[1.3, 3.18, 2.609]}>
        <mesh geometry={nodes.Plane021.geometry} material={materials.PaletteMaterial010} />
        <mesh geometry={nodes.Plane021_1.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/scene-transformed.glb')
